// webapp/src/App.jsx

import { useEffect, useState } from 'react';
import './App.css';

// Usa variable de entorno para producción y fallback a localhost para desarrollo
const API_URL = import.meta.env.VITE_API_URL || 'http://localhost:8888/externalapi/photos';

function App() {
  // State for popup user details
  const [popupUser, setPopupUser] = useState(null);
  // States for filters and pagination
  const [title, setTitle] = useState('');
  const [albumTitle, setAlbumTitle] = useState('');
  const [userEmail, setUserEmail] = useState('');
  const [limit, setLimit] = useState(25);
  const [offset, setOffset] = useState(0);
  const [photos, setPhotos] = useState([]);
  const [total, setTotal] = useState(0);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  // Build the API URL with filters and pagination
  function buildUrl() {
    const params = new URLSearchParams();
    if (title) params.append('title', title);
    if (albumTitle) params.append('album.title', albumTitle);
    if (userEmail) params.append('album.user.email', userEmail);
    params.append('limit', limit);
    params.append('offset', offset);
    return `${API_URL}?${params.toString()}`;
  }

  // Fetch data from API
  useEffect(() => {
    setLoading(true);
    setError('');
    fetch(buildUrl())
      .then(res => {
        if (!res.ok) throw new Error('Failed to fetch data');
        return res.json();
      })
      .then(data => {
        setPhotos(data.data);
        setTotal(data.total);
      })
      .catch(err => setError(err.message))
      .finally(() => setLoading(false));
    // eslint-disable-next-line
  }, [title, albumTitle, userEmail, limit, offset]);

  // Handlers for filters and pagination
  const handleFilter = (e) => {
    e.preventDefault();
    setOffset(0); // Reset pagination when filtering
  };

  // When limit changes, reset offset to 0
  const handleLimitChange = (e) => {
    setLimit(Number(e.target.value));
    setOffset(0);
  };

  const handlePageChange = (newOffset) => {
    // If the new offset is greater than total, go to the last valid page
    if (newOffset >= total) {
      setOffset(Math.max(0, (Math.ceil(total / limit) - 1) * limit));
    } else {
      setOffset(newOffset);
    }
  };

  const totalPages = Math.ceil(total / limit);
  const currentPage = Math.floor(offset / limit) + 1;

  return (
    <div className="container">
      <h1>MetaPhoto - Photo Gallery</h1>
      <form className="filters" onSubmit={handleFilter}>
        <input
          type="text"
          placeholder="Filter by photo title"
          value={title}
          onChange={e => setTitle(e.target.value)}
        />
        <input
          type="text"
          placeholder="Filter by album title"
          value={albumTitle}
          onChange={e => setAlbumTitle(e.target.value)}
        />
        <input
          type="text"
          placeholder="Filter by user email"
          value={userEmail}
          onChange={e => setUserEmail(e.target.value)}
        />
        <button type="submit">Filter</button>
      </form>
      <div className="pagination-controls">
        <label>
          Page size:
          <select value={limit} onChange={handleLimitChange}>
            {[10, 25, 50].map(size => (
              <option key={size} value={size}>{size}</option>
            ))}
          </select>
        </label>
        <button onClick={() => handlePageChange(Math.max(0, offset - limit))} disabled={offset === 0}>
          Previous
        </button>
        <span>Page {currentPage} of {totalPages || 1}</span>
        <button onClick={() => handlePageChange(offset + limit)} disabled={offset + limit >= total}>
          Next
        </button>
      </div>
      {loading && <p>Loading...</p>}
      {error && <p style={{ color: 'red' }}>{error}</p>}
      <div className="photos-grid">
        {photos.map(photo => (
          <div key={photo.id} className="photo-card">
            <img src={photo.thumbnailUrl} alt={photo.title} />
            <h3>{photo.title}</h3>
            <p><b>Album:</b> {photo.album.title}</p>
            <p><b>User:</b> {photo.album.user.name} ({photo.album.user.email})</p>
            <button onClick={() => setPopupUser(photo)}>User Details</button>
          </div>
        ))}
      </div>
      {popupUser && (
        <div className="popup-overlay" style={{position:'fixed',top:0,left:0,width:'100vw',height:'100vh',background:'rgba(0,0,0,0.5)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000}}>
          <div className="popup-content" style={{background:'#2d323c',color:'#fff',padding:'2rem',borderRadius:'8px',maxWidth:'400px',width:'90%',position:'relative',boxShadow:'0 2px 16px rgba(0,0,0,0.25)'}}>
            <button style={{position:'absolute',top:10,right:10,background:'#444',color:'#fff',border:'none',padding:'0.5rem 1rem',borderRadius:'4px',cursor:'pointer',fontWeight:'bold'}} onClick={() => setPopupUser(null)}>Close</button>
            <h2 style={{color:'#fff'}}>User Details</h2>
            <ul style={{color:'#fff',fontSize:'1rem',lineHeight:'1.6'}}>
              <li><b>Photo ID:</b> {popupUser.id}</li>
              <li><b>Album ID:</b> {popupUser.album.id}</li>
              <li><b>Username:</b> {popupUser.album.user.username}</li>
              <li><b>Email:</b> {popupUser.album.user.email}</li>
              <li><b>Phone:</b> {popupUser.album.user.phone}</li>
              <li><b>Website:</b> {popupUser.album.user.website}</li>
              <li><b>Company:</b> {popupUser.album.user.company.name}</li>
              <li><b>Address:</b> {popupUser.album.user.address.street}, {popupUser.album.user.address.city}</li>
            </ul>
          </div>
        </div>
      )}
      {photos.length === 0 && !loading && <p>No results found.</p>}
    </div>
  );
}

export default App;

// web_app/meta-photo-app/src/App.vue
<template>
  <div style="max-width: 700px; margin: auto; padding: 1rem;">
    <h1>Photo Gallery</h1>

    <div style="margin-bottom: 1rem;">
      <input
        v-model="filters.title"
        @input="onFilterChange"
        placeholder="Filter by photo title"
        style="margin-right: 0.5rem;"
      />
      <input
        v-model="filters.albumTitle"
        @input="onFilterChange"
        placeholder="Filter by album title"
        style="margin-right: 0.5rem;"
      />
      <input
        v-model="filters.userEmail"
        @input="onFilterChange"
        placeholder="Filter by user email"
      />
    </div>

    <div style="margin-bottom: 1rem;">
      <label>
        Items per page:
        <select v-model.number="limit" @change="onLimitChange">
          <option :value="10">10</option>
          <option :value="25">25</option>
          <option :value="50">50</option>
        </select>
      </label>
    </div>

    <div v-if="loading">Loading photos...</div>
    <div v-else>
      <div v-if="photos.length === 0">No photos found.</div>
      <div v-else>
        <div
          v-for="photo in photos"
          :key="photo.id"
          style="border: 1px solid #ccc; margin-bottom: 0.8rem; padding: 0.5rem; border-radius: 5px;"
        >
          <h3>{{ photo.title }}</h3>
          <p>
            Album: {{ photo.album.title }} <br />
            User: {{ photo.album.user.name }} ({{ photo.album.user.email }})
          </p>
          <img :src="photo.thumbnailUrl" alt="thumbnail" style="max-width: 150px;" />
        </div>

        <div style="margin-top: 1rem;">
          <button :disabled="offset === 0" @click="prevPage">Prev</button>
          <button
            :disabled="offset + limit >= total"
            @click="nextPage"
            style="margin-left: 1rem;"
          >
            Next
          </button>
        </div>
        <p>
          Page {{ currentPage }} of {{ totalPages }} |
          Total items: {{ total }}
        </p>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, reactive, computed } from "vue";

const photos = ref([]);
const total = ref(0);
const limit = ref(25);
const offset = ref(0);
const loading = ref(false);

const filters = reactive({
  title: "",
  albumTitle: "",
  userEmail: "",
});

// API URL - para desarrollo local usa localhost:8888, para producción usa rutas relativas
const API_URL = import.meta.env.DEV 
  ? "http://localhost:8888/externalapi/photos" 
  : "/api/photos";

async function fetchPhotos() {
  loading.value = true;
  try {
    const params = new URLSearchParams();
    if (filters.title) params.append("title", filters.title);
    if (filters.albumTitle) params.append("album.title", filters.albumTitle);
    if (filters.userEmail) params.append("album.user.email", filters.userEmail);
    params.append("limit", limit.value);
    params.append("offset", offset.value);

    const response = await fetch(`${API_URL}?${params.toString()}`);
    const data = await response.json();

    photos.value = data.data;
    total.value = data.total;
  } catch (error) {
    console.error("Error fetching photos:", error);
    photos.value = [];
    total.value = 0;
  } finally {
    loading.value = false;
  }
}

const currentPage = computed(() => Math.floor(offset.value / limit.value) + 1);
const totalPages = computed(() =>
  Math.ceil(total.value / limit.value)
);

function prevPage() {
  if (offset.value >= limit.value) {
    offset.value -= limit.value;
    fetchPhotos();
  }
}

function nextPage() {
  if (offset.value + limit.value < total.value) {
    offset.value += limit.value;
    fetchPhotos();
  }
}

function onFilterChange() {
  offset.value = 0; // Reset to first page when filter changes
  fetchPhotos();
}

function onLimitChange() {
  offset.value = 0; // Reset to first page when limit changes
  fetchPhotos();
}

// Inicializa datos
fetchPhotos();
</script>
